/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  // presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        pop_black: ["Poppins-Black", "sans-serif"],
        pop_bold: ["Poppins-Bold", "sans-serif"],
        pop_extrabold: ["Poppins-ExtraBold", "sans-serif"],
        pop_extralight: ["Poppins-ExtraLight", "sans-serif"],
        pop_light: ["Poppins-Light", "sans-serif"],
        pop_medium: ["Poppins-Medium", "sans-serif"],
        pop_regular: ["Poppins-Regular", "sans-serif"],
        pop_semibold: ["Poppins-SemiBold", "sans-serif"],
        pop_thin: ["Poppins-Thin", "sans-serif"],

        nun_black: ["NunitoSans-Black", "sans-serif"],
        nun_blackitalic: ["NunitoSans-BlackItalic", "sans-serif"],
        nun_bold: ["NunitoSans-Bold", "sans-serif"],
        nun_bolditalic: ["NunitoSans-BoldItalic", "sans-serif"],
        nun_extrabold: ["NunitoSans-ExtraBold", "sans-serif"],
        nun_extrabolditalic: ["NunitoSans-ExtraBoldItalic", "sans-serif"],
        nun_extralight: ["NunitoSans-ExtraLight", "sans-serif"],
        nun_extralightitalic: ["NunitoSans-ExtraLightItalic", "sans-serif"],
        nun_italic: ["NunitoSans-Italic", "sans-serif"],
        nun_light: ["NunitoSans-Light", "sans-serif"],
        nun_lightitalic: ["NunitoSans-LightItalic", "sans-serif"],
        nun_regular: ["NunitoSans-Regular", "sans-serif"],
        nun_semibold: ["NunitoSans-SemiBold", "sans-serif"],
        nun_semibolditalic: ["NunitoSans-SemiBoldItalic", "sans-serif"],

        jos_bold: ["JosefinSans-Bold", "sans-serif"],
        jos_bolditalic: ["JosefinSans-BoldItalic", "sans-serif"],
        jos_extralight: ["JosefinSans-ExtraLight", "sans-serif"],
        jos_extralightitalic: ["JosefinSans-ExtraLightItalic", "sans-serif"],
        jos_italic: ["JosefinSans-Italic", "sans-serif"],
        jos_light: ["JosefinSans-Light", "sans-serif"],
        jos_lightitalic: ["JosefinSans-LightItalic", "sans-serif"],
        jos_medium: ["JosefinSans-Medium", "sans-serif"],
        jos_mediumitalic: ["JosefinSans-MediumItalic", "sans-serif"],
        jos_regular: ["JosefinSans-Regular", "sans-serif"],
        jos_semibold: ["JosefinSans-SemiBold", "sans-serif"],
        jos_semibolditalic: ["JosefinSans-SemiBoldItalic", "sans-serif"],
        jos_thin: ["JosefinSans-Thin", "sans-serif"],
        jos_thinitalic: ["JosefinSans-ThinItalic", "sans-serif"],
      },
      colors: {
        "primary-1": "#31013F",
        "primary-2": "#690895",
        "primary-3": "#BA7DB0",
        "secondary-1": "#F9D264",
        "secondary-2": "#E9A400",
        "secondary-3": "#601C0E",
        white: "#FFFFFF",
        black: "#000000",
        gray: {
          100: "#F5F5F5",
          200: "#E5E5E5",
          300: "#D4D4D4",
          400: "#A3A3A3",
          500: "#737373",
          600: "#525252",
          700: "#404040",
          800: "#262626",
          900: "#171717",
        },
      },
    },
  },
  future: {
    hoverOnlyWhenSupported: true,
  },
  plugins: [],
};
